<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.istream</groupId>
        <artifactId>yh-istream</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>yh-istream-oss</artifactId>
    <packaging>jar</packaging>
    <name>yh-istream-oss</name>
    <description>对象存储模块：本地存储、阿里云OSS、腾讯云COS、MinIO 等</description>

    <dependencies>
        <!-- 内部依赖 -->
        <dependency>
            <groupId>com.istream</groupId>
            <artifactId>yh-istream-framework</artifactId>
        </dependency>

        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>