/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ai/': RouteRecordInfo<
      '/ai/',
      '/ai',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/403': RouteRecordInfo<
      '/error/403',
      '/error/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/404': RouteRecordInfo<
      '/error/404',
      '/error/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/generator/': RouteRecordInfo<
      '/generator/',
      '/generator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/message/list/': RouteRecordInfo<
      '/message/list/',
      '/message/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/login-info/': RouteRecordInfo<
      '/monitor/login-info/',
      '/monitor/login-info',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/oper-log/': RouteRecordInfo<
      '/monitor/oper-log/',
      '/monitor/oper-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/config/': RouteRecordInfo<
      '/system/config/',
      '/system/config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dept/': RouteRecordInfo<
      '/system/dept/',
      '/system/dept',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dict/': RouteRecordInfo<
      '/system/dict/',
      '/system/dict',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/file/': RouteRecordInfo<
      '/system/file/',
      '/system/file',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/menu/': RouteRecordInfo<
      '/system/menu/',
      '/system/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/role/': RouteRecordInfo<
      '/system/role/',
      '/system/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/user/': RouteRecordInfo<
      '/system/user/',
      '/system/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/ai/index.vue': {
      routes:
        | '/ai/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/error/403.vue': {
      routes:
        | '/error/403'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/error/404.vue': {
      routes:
        | '/error/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/generator/index.vue': {
      routes:
        | '/generator/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/message/list/index.vue': {
      routes:
        | '/message/list/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/login-info/index.vue': {
      routes:
        | '/monitor/login-info/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/oper-log/index.vue': {
      routes:
        | '/monitor/oper-log/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/config/index.vue': {
      routes:
        | '/system/config/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/dept/index.vue': {
      routes:
        | '/system/dept/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/dict/index.vue': {
      routes:
        | '/system/dict/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/file/index.vue': {
      routes:
        | '/system/file/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/menu/index.vue': {
      routes:
        | '/system/menu/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/role/index.vue': {
      routes:
        | '/system/role/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/user/index.vue': {
      routes:
        | '/system/user/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
